/**
 * created by zhao at 2017-3-20
 */

/**首页 */
export const HOME_UPDATE = 'HOME_UPDATE'
//等级圆圈动画事件
export const UPDATE_ANIMATION_GRADE = "UPDATE_ANIMATION_GRADE"
//显示首页帮助视图
export const OPEN_HELP_VIEW = "OPEN_HELP_VIEW"
//关闭首页帮助视图
export const CLOSE_HELP_VIEW = "CLOSE_HELP_VIEW"

//风险中心
export const RISK_CENTER_UPDATE = "RISK_CENTER_UPDATE"
//
export const SWITCH_TAB_RISK_MESSAGE = "SWITCH_TAB_RISK_MESSAGE"

export const SWITCH_RISK_CHECKBOX = "SWITCH_RISK_CHECKBOX"

export const RISK_SELECT_CHANGE = "RISK_SELECT_CHANGE"

export const SAVE_RISK_CENTER_MESSAGE = "SAVE_RISK_CENTER_MESSAGE"

export const SHOW_MODAL = "SHOW_MODAL"

export const HIDE_MODAL = "HIDE_MODAL"


/**成为会员opentip */
export const INIT_OPENTIP = "INIT_OPENTIP"

// 安全等级
export const SAFE_DATA = "SAFE_DATA"

// 自助解纷
export const DE_STEP_ONE = "DE_STEP_ONE"
export const DE_STEP_Two = "DE_STEP_Two"
export const DE_STEP_TWO_GETMSG  = "DE_STEP_TWO_GETMSG "
export const DE_STEP_TWO_COMFIRM = "DE_STEP_TWO_COMFIRM"

//确认支付
export const PAY_MONEY = "PAY_MONEY"

/**我的足迹 */
export const INIT_MYFOOTER = "INIT_MYFOOTER"
export const INIT_MYFOOTER_DETAIL = "INIT_MYFOOTER_DETAIL"

/**安全画像 */
export const RECEIVE_DEVICE_LBS = "RECEIVE_DEVICE_LBS"
export const RECEIVE_DEVICE_INFO = "RECEIVE_DEVICE_INFO"
export const RECEIVE_PASS_DATA = "RECEIVE_PASS_DATA"
export const RECEIVE_PLACE_DATA = "RECEIVE_PLACE_DATA"
export const RECEIVE_CARD_DATA = "RECEIVE_CARD_DATA"
export const RECEIVE_MOBILE_DATA = "RECEIVE_MOBILE_DATA"

/**可信设备 */
export const INIT_TRUSTED_DEVICE = "INIT_TRUSTED_DEVICE"
export const BIND_TRUSTED_DEVICE = "BIND_TRUSTED_DEVICE"
export const UNBIND_TRUSTED_DEVICE = "UNBIND_TRUSTED_DEVICE"
export const INIT_DEVICE_INFO = "INIT_DEVICE_INFO"